import {
  SeniorProfile,
  VolunteerProfile,
  ProfessionalProfile,
  CareRequest,
  GoldenWish,
  LifeStoryChapter,
  VisitAuditLog
} from '../../shared/types';

export const INITIAL_SENIORS: SeniorProfile[] = [
  {
    id: 'senior-1',
    name: 'Margaret Higgins',
    preferredName: 'Maggie',
    age: 78,
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=240&auto=format&fit=crop&q=80',
    neighborhood: 'Oakridge / Westside',
    bio: 'Retired high school literature teacher. Widowed 4 years ago. My grandchildren live abroad in Edinburgh. I love chamomile tea, classic novels, tending to my indoor ferns, and sharing stories from the 1960s.',
    interests: ['Classic Literature', 'Gardening', 'Classical Music', 'Baking Pies', 'History'],
    languages: ['English', 'Conversational French'],
    mobilityNotes: 'Walks comfortably with a cane. Stairs can be tiring.',
    dietaryRestrictions: 'Low sodium, prefers decaf tea',
    safetyPin: '4821', // Arriving volunteer must recite this or match elder's screen
    guardianContact: {
      name: 'David Higgins (Son)',
      relationship: 'Son (lives in Chicago)',
      phone: '+1 (555) 438-9201',
      email: 'david.higgins@example.com',
      notificationPreferences: ['Daily Check-in Alerts', 'Visit Start/End Notices', 'Emergency SOS'],
    },
    dailyCheckIn: {
      checkedInToday: true,
      lastCheckInTime: '8:45 AM Today',
      mood: 'peaceful',
      checkInStreak: 19,
    },
  },
  {
    id: 'senior-2',
    name: 'Arthur Vance',
    preferredName: 'Art',
    age: 84,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=240&auto=format&fit=crop&q=80',
    neighborhood: 'Greenwood Heights',
    bio: 'Former architectural carpenter and craftsman. Avid jazz enthusiast. Have a box of 400 old film photos that I want to digitize so my grandkids can see them.',
    interests: ['Woodworking', '1950s Jazz', 'Model Trains', 'Local History', 'Scrabble'],
    languages: ['English'],
    mobilityNotes: 'Mild arthritis in hands, otherwise fully ambulatory.',
    dietaryRestrictions: 'None',
    safetyPin: '7394',
    guardianContact: {
      name: 'Claire Vance (Daughter)',
      relationship: 'Daughter (lives 40 miles away)',
      phone: '+1 (555) 892-3341',
      email: 'claire.vance@example.com',
      notificationPreferences: ['Daily Check-in Alerts', 'Visit Notices'],
    },
    dailyCheckIn: {
      checkedInToday: false,
      mood: 'need_talk',
      checkInStreak: 12,
    },
  },
];

export const INITIAL_VOLUNTEERS: VolunteerProfile[] = [
  {
    id: 'vol-1',
    name: 'David Chen',
    age: 31,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&auto=format&fit=crop&q=80',
    profession: 'UX Designer & Community Tutor',
    neighborhood: 'Oakridge (0.8 miles from Maggie)',
    bio: 'My beloved grandmother lived with us throughout my childhood. Since her passing, I miss sharing Sunday tea and listening to lived wisdom. Happy to help with tech, groceries, or just companionable conversation.',
    verificationTier: 'tier_3_certified_senior_companion',
    idVerified: true,
    criminalBackgroundCleared: true,
    referenceCheckCleared: true,
    trainingModulesCompleted: [
      'Elder Dignity & Empathy',
      'Dementia & Memory Care Awareness',
      'Financial Exploitation Prevention',
      'Emergency First Response',
      'Physical Transfer & Fall Safety Protocols'
    ],
    trustScore: 99,
    completedVisitsCount: 34,
    volunteerHours: 58,
    languages: ['English', 'Mandarin'],
    skills: ['Patient Tech Tutoring', 'Story Archiving', 'Grocery Assistance', 'Card Games'],
    badges: ['Top Companion 2024', 'Background Cleared ★★★', 'Empathy Certified', 'Punctual Helper'],
    reviewsCount: 29,
    rating: 4.96,
  },
  {
    id: 'vol-2',
    name: 'Elena Rostova',
    age: 26,
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=240&auto=format&fit=crop&q=80',
    profession: 'Graduate Student in Literature',
    neighborhood: 'Westside Heights',
    bio: 'Passionate about listening to oral histories and reading aloud. Certified in CPR/AED. Can accompany to botanical gardens, grocery runs, or quiet afternoon reading sessions.',
    verificationTier: 'tier_3_certified_senior_companion',
    idVerified: true,
    criminalBackgroundCleared: true,
    referenceCheckCleared: true,
    trainingModulesCompleted: [
      'Elder Dignity & Empathy',
      'Boundaries & Family Communication',
      'Active Listening Techniques'
    ],
    trustScore: 97,
    completedVisitsCount: 19,
    volunteerHours: 36,
    languages: ['English', 'Spanish'],
    skills: ['Reading Aloud', 'Letter Writing', 'Gentle Walks', 'Audio Recording'],
    badges: ['Background Cleared ★★★', 'Story Keeper'],
    reviewsCount: 16,
    rating: 4.9,
  },
  {
    id: 'vol-3',
    name: 'Samuel Rivera',
    age: 42,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=240&auto=format&fit=crop&q=80',
    profession: 'High School Science Teacher',
    neighborhood: 'Greenwood Heights',
    bio: 'Father of two. Love helping elders with heavy groceries, setting up smartphones, fixing squeaky doors, or playing a game of chess.',
    verificationTier: 'tier_2_background_cleared',
    idVerified: true,
    criminalBackgroundCleared: true,
    referenceCheckCleared: true,
    trainingModulesCompleted: [
      'Elder Dignity & Empathy',
      'Safe Transportation Guidelines'
    ],
    trustScore: 94,
    completedVisitsCount: 8,
    volunteerHours: 16,
    languages: ['English'],
    skills: ['Household Fixes', 'Chess', 'Phone Setup', 'Errands'],
    badges: ['Background Cleared ★★'],
    reviewsCount: 7,
    rating: 4.85,
  }
];

export const INITIAL_PROFESSIONALS: ProfessionalProfile[] = [
  {
    id: 'pro-1',
    name: 'Sarah Jenkins, RN, BSN',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=240&auto=format&fit=crop&q=80',
    profession: 'Nurse (RN/BSN)',
    licenseNumber: 'RN-88412-CA (Active & Verified)',
    issuingBoard: 'State Board of Registered Nursing',
    yearsOfExperience: 14,
    verifiedCredentials: true,
    verificationBadge: 'Board Verified Clinician',
    specialties: ['Geriatric Wellness', 'Fall Risk Prevention', 'Medication Reconciliation Support', 'Post-Hospitalization Care'],
    bio: 'Senior nurse specializing in geriatric home health and wellness education. I ensure seniors understand their care instructions with warmth and compassion.',
    servicesOffered: [
      'Home Fall-Safety Audit',
      'Medication Schedule Organization',
      'Vital Signs & Blood Pressure Check',
      'Post-Discharge Care Plan Consultation'
    ],
    rating: 5.0,
    reviewsCount: 42,
    isAvailableForProBono: true,
  },
  {
    id: 'pro-2',
    name: 'Dr. Marcus Wells, MD',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=240&auto=format&fit=crop&q=80',
    profession: 'Doctor',
    licenseNumber: 'MD-41092-CA (Active & Verified)',
    issuingBoard: 'Medical Board of California - Geriatric Medicine',
    yearsOfExperience: 22,
    verifiedCredentials: true,
    verificationBadge: 'Board Certified Geriatrician',
    specialties: ['Geriatric Medicine', 'Memory Assessment', 'Chronic Condition Management'],
    bio: 'Dedicated to helping older adults navigate healthcare transitions and maintain independence with the utmost dignity.',
    servicesOffered: [
      'Geriatric Health Consult',
      'Second Opinion on Care Pathways',
      'Cognitive Health Screening Advice'
    ],
    rating: 4.98,
    reviewsCount: 56,
    isAvailableForProBono: true,
  },
  {
    id: 'pro-3',
    name: 'Miriam Vance-Lee, LCSW',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=240&auto=format&fit=crop&q=80',
    profession: 'Social Worker (LCSW)',
    licenseNumber: 'LCSW-29402 (Active & Verified)',
    issuingBoard: 'Board of Behavioral Sciences',
    yearsOfExperience: 11,
    verifiedCredentials: true,
    verificationBadge: 'Licensed Clinical Social Worker',
    specialties: ['Elder Emotional Support', 'Grief & Bereavement', 'Family Caregiver Mediation'],
    bio: 'Compassionate licensed social worker helping seniors navigate grief, life transitions, and community support benefits.',
    servicesOffered: [
      'Emotional Support & Loneliness Counseling',
      'Navigating Senior Community Benefits',
      'Advance Care Directive Guidance'
    ],
    rating: 4.95,
    reviewsCount: 31,
    isAvailableForProBono: true,
  }
];

export const INITIAL_REQUESTS: CareRequest[] = [
  {
    id: 'req-1',
    seniorId: 'senior-1',
    seniorName: 'Margaret Higgins',
    seniorAge: 78,
    seniorAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=240&auto=format&fit=crop&q=80',
    neighborhood: 'Oakridge',
    title: 'Friendly Afternoon Tea & Poetry Reading',
    category: 'conversation',
    priority: 'routine',
    description: 'I would love a companion to visit for an hour, have a cup of chamomile tea, and read some Emily Dickinson or Mary Oliver poetry together. My living room gets lovely sunlight at 3 PM.',
    dateNeeded: 'Tomorrow at 3:00 PM',
    estimatedDuration: '1.5 hours',
    status: 'matched',
    safetyNotes: 'Visit in living room with front door clear. Host has a friendly indoor cat named Barnaby.',
    assignedVolunteerId: 'vol-1',
    assignedVolunteerName: 'David Chen',
    assignedVolunteerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&auto=format&fit=crop&q=80',
    safetyPin: '4821',
    createdAt: '2026-09-17',
  },
  {
    id: 'req-2',
    seniorId: 'senior-1',
    seniorName: 'Margaret Higgins',
    seniorAge: 78,
    seniorAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=240&auto=format&fit=crop&q=80',
    neighborhood: 'Oakridge',
    title: 'Fresh Grocery Delivery from Farmers Market',
    category: 'groceries',
    priority: 'routine',
    description: 'Need help picking up 2 cartons of almond milk, fresh spinach, honeycrisp apples, and whole grain oats from the community grocery. Items will be reimbursed directly or receipt verified.',
    dateNeeded: 'Saturday morning (10:00 AM)',
    estimatedDuration: '1 hour',
    status: 'open',
    safetyNotes: 'Delivery to front porch; volunteer can bring groceries inside if desired and signed off.',
    safetyPin: '4821',
    createdAt: '2026-09-18',
  },
  {
    id: 'req-3',
    seniorId: 'senior-2',
    seniorName: 'Arthur Vance',
    seniorAge: 84,
    seniorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=240&auto=format&fit=crop&q=80',
    neighborhood: 'Greenwood Heights',
    title: 'Help Scanning 1960s Family Photos to iPad',
    category: 'tech_help',
    priority: 'routine',
    description: 'I have a collection of 50 black-and-white photos of my late wife and our first carpentry workshop. I want to learn how to scan them onto the iPad my daughter sent me.',
    dateNeeded: 'Friday at 2:00 PM',
    estimatedDuration: '2 hours',
    status: 'open',
    safetyNotes: 'Arthur prefers slow, patient explanations with handwritten cheat-sheets.',
    safetyPin: '7394',
    createdAt: '2026-09-18',
  },
  {
    id: 'req-4',
    seniorId: 'senior-1',
    seniorName: 'Margaret Higgins',
    seniorAge: 78,
    seniorAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=240&auto=format&fit=crop&q=80',
    neighborhood: 'Oakridge',
    title: 'Professional Fall-Safety & Balance Check',
    category: 'professional_care',
    priority: 'scheduled',
    description: 'Margaret slipped slightly last month on the kitchen mat. Requesting a verified licensed nurse or physical therapist to inspect living area rugs, threshold strips, and review balance exercises.',
    dateNeeded: 'Next Tuesday at 11:00 AM',
    estimatedDuration: '1 hour',
    status: 'matched',
    safetyNotes: 'Professional verification mandatory. General volunteers are not permitted to accept clinical safety tasks.',
    assignedProfessionalId: 'pro-1',
    assignedProfessionalName: 'Sarah Jenkins, RN',
    assignedProfessionalRole: 'Nurse (RN/BSN)',
    safetyPin: '4821',
    isProfessionalOnly: true,
    createdAt: '2026-09-16',
  }
];

export const INITIAL_GOLDEN_WISHES: GoldenWish[] = [
  {
    id: 'wish-1',
    seniorId: 'senior-1',
    seniorName: 'Margaret Higgins',
    seniorAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=240&auto=format&fit=crop&q=80',
    title: 'Hear Chopin’s Nocturne in E-flat played live on piano',
    description: 'When I was 19, my mother saved money for six months so I could attend a conservatory concert. I would love to hear someone play Chopin live in my parlor on my vintage spinet piano.',
    category: 'nostalgia',
    status: 'pledged',
    pledgedByVolunteerName: 'David Chen (arranging with music student)',
    fulfillmentNotes: 'David coordinated with a local conservatory student to perform a 20-minute private recital on Saturday.',
    createdAt: '2026-09-12'
  },
  {
    id: 'wish-2',
    seniorId: 'senior-2',
    seniorName: 'Arthur Vance',
    seniorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=240&auto=format&fit=crop&q=80',
    title: 'Visit the Harbor Pier to smell the ocean air again',
    description: 'Haven’t seen the tide roll in under the lighthouse since 2021. I want to sit on a dry bench with a hot clam chowder cup and watch the gulls for an hour.',
    category: 'outing',
    status: 'open',
    createdAt: '2026-09-15'
  },
  {
    id: 'wish-3',
    seniorId: 'senior-1',
    seniorName: 'Margaret Higgins',
    seniorAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=240&auto=format&fit=crop&q=80',
    title: 'Learn the basics of botanical watercolor painting',
    description: 'I always admired botanical illustrations in Victorian books. I would cherish a patient afternoon learning how to paint a simple lavender sprig.',
    category: 'creative',
    status: 'open',
    createdAt: '2026-09-17'
  }
];

export const INITIAL_LIFE_STORIES: LifeStoryChapter[] = [
  {
    id: 'story-1',
    seniorId: 'senior-1',
    seniorName: 'Margaret Higgins',
    title: 'The Blue Bicycle & The Great Library of 1958',
    theme: 'Early Memories',
    promptQuestion: 'What was your favorite childhood possession, and where did it take you?',
    audioDuration: '4 mins 20 secs',
    transcript: 'My father worked at the rail yard, and when I turned twelve, he rebuilt a heavy navy-blue bicycle from spare parts. That bicycle was my chariot to the Carnegie Public Library six miles away. The librarian, Miss Albright, would keep the leather-bound classics set aside for me under the counter. That small kindness ignited my forty years of teaching literature.',
    refinedStory: 'A hand-built navy-blue bicycle became Margaret’s gateway to literature and learning. Riding through quiet country roads to the Carnegie Library in 1958, a librarian’s quiet faith in a 12-year-old girl sparked four decades of devoted teaching.',
    lifeLessonTakeaway: 'Small investments in a child’s curiosity can quietly change the trajectory of an entire life.',
    recordedDate: 'September 14, 2026',
    isSharedWithFamily: true
  },
  {
    id: 'story-2',
    seniorId: 'senior-1',
    seniorName: 'Margaret Higgins',
    title: 'Fifty-One Winters: What Holds Two People Together',
    theme: 'Love & Family',
    promptQuestion: 'What did half a century of marriage teach you about true companionship?',
    audioDuration: '5 mins 45 secs',
    transcript: 'Robert and I disagreed on plenty—he liked the radio loud, I wanted peace; he was always ten minutes early, I was perpetually looking for my cardigan. But whenever life hit hard, we made tea first before speaking. True love isn’t the fireworks of youth; it’s someone who knows how you take your tea and leaves a warm blanket across your knees when you fall asleep reading.',
    refinedStory: 'Reflections on fifty-one years of marriage with Robert. The enduring truth that real love is forged in tiny courtesies, patience through disagreement, and the quiet comfort of presence.',
    lifeLessonTakeaway: 'When trouble knocks at the door, put the kettle on first. Kindness is a daily discipline, not a mood.',
    recordedDate: 'September 16, 2026',
    isSharedWithFamily: true
  }
];

export const INITIAL_AUDIT_LOGS: VisitAuditLog[] = [
  {
    id: 'audit-1',
    requestId: 'req-101',
    seniorName: 'Margaret Higgins',
    volunteerName: 'David Chen',
    scheduledTime: 'Yesterday, 3:00 PM - 4:30 PM',
    checkInTime: '3:03 PM',
    checkOutTime: '4:28 PM',
    verifiedWithPin: true,
    seniorSatisfaction: 5,
    notes: 'Wonderful visit. We sat on the sun porch and talked about Margaret’s teaching days. She showed me her award from the Westside School Board.',
    familyNotified: true,
  },
  {
    id: 'audit-2',
    requestId: 'req-102',
    seniorName: 'Arthur Vance',
    volunteerName: 'Elena Rostova',
    scheduledTime: 'Sep 15, 1:00 PM - 2:30 PM',
    checkInTime: '1:00 PM',
    checkOutTime: '2:25 PM',
    verifiedWithPin: true,
    seniorSatisfaction: 5,
    notes: 'Listened to Miles Davis album together while Arthur labeled woodworking blueprints for his grandson.',
    familyNotified: true,
  }
];
